//! The language-pack file format: one JSON document per language, used for
//! bundled translations, user-installed translations, and the
//! export → translate → import round trip.
//!
//! ```json
//! {
//!   "format": 1,
//!   "code": "fr",
//!   "name": "Français",
//!   "english_name": "French",
//!   "instructions": "…how to translate this file… (optional)",
//!   "strings": {
//!     "Open": "Ouvrir",
//!     "menu::Open": "Ouvrir",
//!     "{n} file": { "one": "{n} fichier", "other": "{n} fichiers" }
//!   },
//!   "untranslated": { "Move to Trash": "Move to Trash" }
//! }
//! ```
//!
//! `strings` holds translations keyed by the English msgid. `untranslated`
//! is only present in an exported template: it lists the msgids that still
//! need work, with their English text as the value, so a translator (or an
//! LLM) translates and moves each one into `strings`. On import only
//! `strings` is read.
//!
//! `locales/en.json` uses the same shape with English values and is the
//! canonical list of every msgid in the code (generated by
//! [`super::extract`]).

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};

/// The generated source catalog: every msgid in the workspace.
pub const EN_JSON: &str = include_str!("../../../../locales/en.json");

/// Translations shipped inside the binary. A user pack with the same code
/// (in the config dir) takes precedence, so anyone can fix a string
/// locally before contributing it back.
pub const BUNDLED: &[(&str, &str)] = &[
    ("fr", include_str!("../../../../locales/fr.json")),
    ("de", include_str!("../../../../locales/de.json")),
    // Contributed by Bohun (github.com/bohunamiga).
    ("pl", include_str!("../../../../locales/pl.json")),
];

/// Current value of [`LanguagePack::format`].
pub const FORMAT: u32 = 1;

/// A single translated value or its plural forms.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PackValue {
    Text(String),
    /// CLDR category name (`one`, `other`, …) → form.
    Plural(BTreeMap<String, String>),
}

impl PackValue {
    /// True when there is something usable to display.
    pub fn is_translated(&self) -> bool {
        match self {
            PackValue::Text(s) => !s.trim().is_empty(),
            PackValue::Plural(forms) => forms.get("other").is_some_and(|s| !s.trim().is_empty()),
        }
    }

    fn texts(&self) -> Vec<&str> {
        match self {
            PackValue::Text(s) => vec![s.as_str()],
            PackValue::Plural(forms) => forms.values().map(String::as_str).collect(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LanguagePack {
    #[serde(default = "default_format")]
    pub format: u32,
    /// BCP-47-ish tag: `fr`, `pt-BR`, `zh-Hant`.
    pub code: String,
    /// The language's own name: `Français`.
    #[serde(default)]
    pub name: String,
    /// The language's English name: `French`.
    #[serde(default)]
    pub english_name: String,
    /// Free-text instructions for whoever translates the file. Written
    /// into exported templates; ignored on import.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub instructions: String,
    #[serde(default)]
    pub strings: BTreeMap<String, PackValue>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub untranslated: BTreeMap<String, PackValue>,
}

fn default_format() -> u32 {
    FORMAT
}

impl LanguagePack {
    pub fn empty(code: &str, name: &str, english_name: &str) -> Self {
        Self {
            format: FORMAT,
            code: code.to_owned(),
            name: name.to_owned(),
            english_name: english_name.to_owned(),
            instructions: String::new(),
            strings: BTreeMap::new(),
            untranslated: BTreeMap::new(),
        }
    }

    /// Parse a pack file. Errors are human-readable (shown in the import
    /// report), never panics.
    pub fn parse(json: &str) -> Result<Self, String> {
        let pack: LanguagePack =
            serde_json::from_str(json).map_err(|e| format!("not a valid language pack: {e}"))?;
        if pack.format > FORMAT {
            return Err(format!(
                "language pack format {} is newer than this Ferail understands ({})",
                pack.format, FORMAT
            ));
        }
        if !is_valid_code(&pack.code) {
            return Err(format!(
                "\"{}\" is not a valid language code (expected something like \"fr\" or \"pt-BR\")",
                pack.code
            ));
        }
        Ok(pack)
    }

    pub fn to_json(&self) -> String {
        // Pretty-printed: people open these files in an editor or hand
        // them to a chat model, and diffs in git should be reviewable.
        serde_json::to_string_pretty(self).unwrap_or_else(|_| "{}".to_owned()) + "\n"
    }

    /// `(translated, total)` against the source catalog.
    pub fn coverage(&self) -> (usize, usize) {
        let src = source();
        let translated = src
            .strings
            .keys()
            .filter(|k| self.strings.get(*k).is_some_and(PackValue::is_translated))
            .count();
        (translated, src.strings.len())
    }

    /// Check a pack against the source catalog. Nothing here is fatal
    /// (a pack with problems still loads, string by string) but the
    /// report tells the user what to fix.
    pub fn validate(&self) -> ValidationReport {
        let src = source();
        let mut report = ValidationReport {
            code: self.code.clone(),
            translated: 0,
            total: src.strings.len(),
            unknown_keys: Vec::new(),
            placeholder_mismatches: Vec::new(),
            bad_plural_categories: Vec::new(),
        };
        for (key, value) in &self.strings {
            let Some(src_value) = src.strings.get(key) else {
                report.unknown_keys.push(key.clone());
                continue;
            };
            if value.is_translated() {
                report.translated += 1;
            }
            let want: BTreeSet<String> = src_value
                .texts()
                .iter()
                .flat_map(|t| placeholders(t))
                .collect();
            for text in value.texts() {
                let have: BTreeSet<String> = placeholders(text).into_iter().collect();
                if have != want {
                    report.placeholder_mismatches.push(key.clone());
                    break;
                }
            }
            if let PackValue::Plural(forms) = value {
                if forms
                    .keys()
                    .any(|c| super::plural::Category::from_name(c).is_none())
                {
                    report.bad_plural_categories.push(key.clone());
                }
            }
        }
        report
    }

    /// Build the file a translator works on: `strings` keeps what is
    /// already translated (restricted to live msgids), `untranslated` lists
    /// everything else with its English text, and `instructions` explains
    /// the job.
    pub fn template(&self) -> LanguagePack {
        let src = source();
        let mut out = LanguagePack::empty(&self.code, &self.name, &self.english_name);
        for (key, value) in &src.strings {
            match self.strings.get(key) {
                Some(t) if t.is_translated() => {
                    out.strings.insert(key.clone(), t.clone());
                }
                _ => {
                    out.untranslated.insert(key.clone(), value.clone());
                }
            }
        }
        let language = if self.english_name.is_empty() {
            self.code.as_str()
        } else {
            self.english_name.as_str()
        };
        out.instructions = instructions_for(language);
        out
    }
}

/// Import/validation outcome, for the UI to render.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ValidationReport {
    pub code: String,
    pub translated: usize,
    pub total: usize,
    /// Keys that no longer exist in the code (harmless; stale).
    pub unknown_keys: Vec<String>,
    /// Keys whose translation lost or invented a `{placeholder}`.
    pub placeholder_mismatches: Vec<String>,
    /// Plural entries with a category name that isn't a CLDR category.
    pub bad_plural_categories: Vec<String>,
}

impl ValidationReport {
    pub fn has_warnings(&self) -> bool {
        !self.unknown_keys.is_empty()
            || !self.placeholder_mismatches.is_empty()
            || !self.bad_plural_categories.is_empty()
    }

    /// Multi-line, English (it is a developer/translator-facing report;
    /// the headline shown in the UI is translated separately).
    pub fn details(&self) -> String {
        let mut s = format!(
            "{} of {} strings translated.\n",
            self.translated, self.total
        );
        if !self.placeholder_mismatches.is_empty() {
            s.push_str(&format!(
                "\n{} translation(s) changed a {{placeholder}}: these will show wrong or missing values:\n",
                self.placeholder_mismatches.len()
            ));
            for k in &self.placeholder_mismatches {
                s.push_str("  • ");
                s.push_str(k);
                s.push('\n');
            }
        }
        if !self.bad_plural_categories.is_empty() {
            s.push_str(&format!(
                "\n{} plural entr(y/ies) use an unknown category (use zero/one/two/few/many/other):\n",
                self.bad_plural_categories.len()
            ));
            for k in &self.bad_plural_categories {
                s.push_str("  • ");
                s.push_str(k);
                s.push('\n');
            }
        }
        if !self.unknown_keys.is_empty() {
            s.push_str(&format!(
                "\n{} key(s) no longer exist in this version of Ferail (ignored):\n",
                self.unknown_keys.len()
            ));
            for k in &self.unknown_keys {
                s.push_str("  • ");
                s.push_str(k);
                s.push('\n');
            }
        }
        s
    }
}

/// The parsed `locales/en.json`.
pub fn source() -> &'static LanguagePack {
    static SOURCE: std::sync::OnceLock<LanguagePack> = std::sync::OnceLock::new();
    SOURCE.get_or_init(|| {
        LanguagePack::parse(EN_JSON).unwrap_or_else(|e| {
            // The generated file is checked by a test; reaching this means a
            // hand edit broke it. Degrade to "nothing is translatable"
            // rather than taking the app down.
            debug_assert!(false, "locales/en.json: {e}");
            LanguagePack::empty("en", "English", "English")
        })
    })
}

/// A bundled pack by code, parsed fresh (cheap; callers cache the
/// resulting `Catalog`).
pub fn bundled(code: &str) -> Option<LanguagePack> {
    let (_, json) = BUNDLED.iter().find(|(c, _)| *c == code)?;
    LanguagePack::parse(json).ok()
}

/// Codes of the bundled packs, in display order.
pub fn bundled_codes() -> impl Iterator<Item = &'static str> {
    BUNDLED.iter().map(|(c, _)| *c)
}

/// `fr`, `pt-BR`, `zh-Hant`, `sr-Latn-RS`: a 2–3 letter language subtag
/// followed by optional 2–8 character alphanumeric subtags.
pub fn is_valid_code(code: &str) -> bool {
    let mut parts = code.split('-');
    let Some(lang) = parts.next() else {
        return false;
    };
    if !(2..=3).contains(&lang.len()) || !lang.chars().all(|c| c.is_ascii_lowercase()) {
        return false;
    }
    parts.all(|p| (2..=8).contains(&p.len()) && p.chars().all(|c| c.is_ascii_alphanumeric()))
}

/// `{name}` placeholders in a template, ignoring `{{` escapes.
pub fn placeholders(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(open) = rest.find('{') {
        let after = &rest[open + 1..];
        if let Some(stripped) = after.strip_prefix('{') {
            rest = stripped;
            continue;
        }
        match after.find('}') {
            Some(close) => {
                let name = &after[..close];
                if !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
                    out.push(name.to_owned());
                }
                rest = &after[close + 1..];
            }
            None => break,
        }
    }
    out
}

/// The translator brief written into exported templates and copied to the
/// clipboard by "Copy translation instructions". Plain English on purpose:
/// it is read by a person or a chat model, not by Ferail.
pub fn instructions_for(language: &str) -> String {
    INSTRUCTIONS.replace("{language}", language)
}

const INSTRUCTIONS: &str = "\
You are translating the user interface of Ferail, a desktop file manager, from English into {language}. \
This JSON file is a Ferail language pack. Please:
1. Translate every entry in \"untranslated\" and move it into \"strings\" (same key, translated value). \
Leave existing \"strings\" entries alone unless they are wrong. When you are done, \"untranslated\" must be empty or removed.
2. Keys are the English source text, never change a key. If a key starts with a word and \"::\" \
(for example \"menu::Open\"), the part before \"::\" is only a context hint; translate the part after it and keep the key verbatim.
3. Keep every {placeholder} exactly as written ({n}, {name}, {dest}, …). You may reorder them. \"{{\" and \"}}\" are literal braces.
4. A value that is an object with \"one\"/\"other\" is a plural. Provide the forms {language} needs, keyed by CLDR category \
(zero, one, two, few, many, other); \"other\" is required. The count is always the {n} placeholder.
5. Write like a native desktop app: short, sentence case, imperative for commands (\"Open\", \"Move to Trash\"), \
no trailing period on labels, keep a trailing \"…\" (it means a dialog follows), keep \"&\" and keyboard names. \
Do not translate product and feature names: Ferail, Finder, Ant Trail, Quick Look, Spotlight, iCloud, OneDrive, macOS, Windows, Linux.
6. Keep translations about as long as the English; they must fit buttons, menus and column headers.
7. Set \"name\" to the language's own name (\"Français\"), \"english_name\" to its English name (\"French\"), \
and \"code\" to its BCP-47 tag (\"fr\", \"pt-BR\").
8. Return the complete file as valid JSON and nothing else. \
Then import it in Ferail: Settings → Appearance → Language → Import…";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_and_roundtrip() {
        let json = r#"{"code":"fr","name":"Français","english_name":"French",
            "strings":{"Open":"Ouvrir","{n} file":{"one":"{n} fichier","other":"{n} fichiers"}}}"#;
        let pack = LanguagePack::parse(json).unwrap();
        assert_eq!(pack.format, FORMAT);
        assert_eq!(pack.strings.len(), 2);
        let again = LanguagePack::parse(&pack.to_json()).unwrap();
        assert_eq!(pack, again);
    }

    #[test]
    fn rejects_bad_code_and_future_format() {
        assert!(LanguagePack::parse(r#"{"code":"French","strings":{}}"#).is_err());
        assert!(LanguagePack::parse(r#"{"format":99,"code":"fr","strings":{}}"#).is_err());
        assert!(LanguagePack::parse("nope").is_err());
    }

    #[test]
    fn code_validation() {
        assert!(is_valid_code("fr"));
        assert!(is_valid_code("pt-BR"));
        assert!(is_valid_code("zh-Hant"));
        assert!(!is_valid_code("FR"));
        assert!(!is_valid_code(""));
        assert!(!is_valid_code("f"));
        assert!(!is_valid_code("fr_FR"));
    }

    #[test]
    fn placeholder_extraction() {
        assert_eq!(placeholders("Copied {n} to {dest}"), vec!["n", "dest"]);
        assert_eq!(placeholders("{{not}} {one}"), vec!["one"]);
        assert!(placeholders("no braces").is_empty());
        assert!(placeholders("{not a name}").is_empty());
    }

    #[test]
    fn bundled_packs_parse() {
        for (code, json) in BUNDLED {
            let pack =
                LanguagePack::parse(json).unwrap_or_else(|e| panic!("locales/{code}.json: {e}"));
            assert_eq!(
                pack.code, *code,
                "locales/{code}.json declares a different code"
            );
        }
    }

    #[test]
    fn bundled_packs_fully_cover_source_catalog() {
        let src = source();
        for (code, json) in BUNDLED {
            let pack =
                LanguagePack::parse(json).unwrap_or_else(|e| panic!("locales/{code}.json: {e}"));
            let report = pack.validate();
            assert_eq!(
                report.translated, report.total,
                "locales/{code}.json is missing translations"
            );
            assert!(
                report.unknown_keys.is_empty(),
                "locales/{code}.json has stale keys: {:?}",
                report.unknown_keys
            );
            assert!(
                report.placeholder_mismatches.is_empty(),
                "locales/{code}.json changed placeholders: {:?}",
                report.placeholder_mismatches
            );
            assert!(
                report.bad_plural_categories.is_empty(),
                "locales/{code}.json has invalid plural categories: {:?}",
                report.bad_plural_categories
            );
            for (key, source_value) in &src.strings {
                let translated = pack
                    .strings
                    .get(key)
                    .unwrap_or_else(|| panic!("locales/{code}.json is missing {key:?}"));
                assert_eq!(
                    std::mem::discriminant(source_value),
                    std::mem::discriminant(translated),
                    "locales/{code}.json changes the text/plural shape of {key:?}"
                );
            }
        }
    }

    #[test]
    fn source_catalog_parses() {
        let src = source();
        assert_eq!(src.code, "en");
    }

    #[test]
    fn validate_reports_placeholder_drift_and_unknown_keys() {
        // Build a pack against whatever the real source catalog holds.
        let src = source();
        let Some((key, value)) = src
            .strings
            .iter()
            .find(|(_, v)| matches!(v, PackValue::Text(t) if !placeholders(t).is_empty()))
        else {
            return; // no placeholder msgids yet, nothing to test
        };
        let PackValue::Text(english) = value else {
            unreachable!()
        };
        let mut pack = LanguagePack::empty("xx", "X", "X");
        pack.strings.insert(
            key.clone(),
            PackValue::Text(english.replace('{', "[").replace('}', "]")),
        );
        pack.strings.insert(
            "this key does not exist".into(),
            PackValue::Text("nope".into()),
        );
        let report = pack.validate();
        assert_eq!(report.placeholder_mismatches, vec![key.clone()]);
        assert_eq!(
            report.unknown_keys,
            vec!["this key does not exist".to_owned()]
        );
        assert!(report.has_warnings());
        assert!(report.details().contains("placeholder"));
    }

    #[test]
    fn template_splits_translated_and_untranslated() {
        let src = source();
        let mut pack = LanguagePack::empty("fr", "Français", "French");
        if let Some((k, _)) = src.strings.iter().next() {
            pack.strings.insert(k.clone(), PackValue::Text("x".into()));
        }
        let t = pack.template();
        assert_eq!(t.strings.len() + t.untranslated.len(), src.strings.len());
        assert!(t.instructions.contains("French"));
        assert_eq!(t.coverage().0, t.strings.len());
    }
}
