[package]
name = "ferail-ntfs-win32"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Windows raw-volume reader and helper boundary for Ferail Fast NTFS"

[dependencies]
ferail-ntfs.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_WindowsProgramming",
] }

[[bin]]
name = "ferail-ntfs-diag"
path = "src/bin/diag.rs"
