[package]
name = "feraille-shell-mac"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "macOS shell integration for Feraille (chrome, drag-drop, NSMenu)"

[dependencies]
feraille-core.workspace = true
winit.workspace = true
png = "0.17"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.5", features = ["exception"] }
objc2-foundation = { version = "0.2", features = [
    "NSURL",
    "NSArray",
    "NSGeometry",
    "NSString",
    "NSData",
    "NSDictionary",
    "NSNotification",
    "NSDistributedNotificationCenter",
] }
objc2-app-kit = { version = "0.2", features = [
    "NSWindow",
    "NSResponder",
    "NSView",
    "NSPasteboard",
    "NSPasteboardItem",
    "NSDragging",
    "NSDraggingItem",
    "NSDraggingSession",
    "NSEvent",
    "NSApplication",
    "NSAppearance",
    "NSCell",
    "NSImage",
    "NSWorkspace",
    "NSMenu",
    "NSMenuItem",
    "NSAlert",
    "NSButton",
    "NSControl",
] }
raw-window-handle = "0.6"
